#  mamba env create --name RNAseq_mapping --file environment.yaml 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake=6.0.3
  - pandas=0.24.2
  - fastqc=0.11.8
  - bbmap=38.22
  - trimmomatic=0.38
  - pigz=2.3.4
  - hisat2=2.1.0
  - star=2.7.0d
  - samtools=1.9
  - deeptools=3.1.3
